/**
 * Comprehensive list of UK universities and higher education institutions.
 * Sources: HESA, UCAS, Universities UK (2024).
 */
export const UK_UNIVERSITIES: string[] = [
  // England — Russell Group
  "University of Birmingham",
  "University of Bristol",
  "University of Cambridge",
  "Cardiff University",
  "Durham University",
  "University of Edinburgh",
  "University of Exeter",
  "University of Glasgow",
  "Imperial College London",
  "King's College London",
  "University of Leeds",
  "University of Liverpool",
  "London School of Economics and Political Science",
  "University of Manchester",
  "Newcastle University",
  "University of Nottingham",
  "University of Oxford",
  "Queen Mary University of London",
  "Queen's University Belfast",
  "University of Sheffield",
  "University of Southampton",
  "University College London",
  "University of Warwick",
  "University of York",

  // England — Other universities
  "Anglia Ruskin University",
  "Aston University",
  "Bath Spa University",
  "University of Bath",
  "University of Bedfordshire",
  "Birmingham City University",
  "University of Bolton",
  "Bournemouth University",
  "BPP University",
  "University of Brighton",
  "Brunel University London",
  "Buckinghamshire New University",
  "University of Central Lancashire",
  "City, University of London",
  "Coventry University",
  "University of Cumbria",
  "De Montfort University",
  "University of Derby",
  "University of East Anglia",
  "University of East London",
  "Edge Hill University",
  "University of Essex",
  "Falmouth University",
  "University of Greenwich",
  "Harper Adams University",
  "University of Hertfordshire",
  "University of Huddersfield",
  "University of Hull",
  "Keele University",
  "University of Kent",
  "Kingston University",
  "Lancaster University",
  "University of Leicester",
  "University of Lincoln",
  "Liverpool Hope University",
  "Liverpool John Moores University",
  "London Metropolitan University",
  "London South Bank University",
  "Loughborough University",
  "Manchester Metropolitan University",
  "Middlesex University",
  "University of Northampton",
  "Northumbria University",
  "Norwich University of the Arts",
  "Nottingham Trent University",
  "Oxford Brookes University",
  "University of Plymouth",
  "University of Portsmouth",
  "University of Reading",
  "Regent's University London",
  "University of Roehampton",
  "Royal Holloway, University of London",
  "University of Salford",
  "Sheffield Hallam University",
  "University of South Wales",
  "Southampton Solent University",
  "St Mary's University, Twickenham",
  "Staffordshire University",
  "University of Suffolk",
  "University of Sunderland",
  "Teesside University",
  "University of the Arts London",
  "University of the West of England, Bristol",
  "University of West London",
  "University of Winchester",
  "University of Wolverhampton",
  "Wrexham University",
  "York St John University",

  // London specialist
  "Goldsmiths, University of London",
  "Guildhall School of Music and Drama",
  "London Business School",
  "London School of Hygiene and Tropical Medicine",
  "Royal Academy of Music",
  "Royal College of Art",
  "Royal College of Music",
  "Royal Veterinary College",
  "SOAS University of London",
  "St George's, University of London",

  // Scotland
  "University of Aberdeen",
  "University of Abertay Dundee",
  "Edinburgh Napier University",
  "University of Dundee",
  "Glasgow Caledonian University",
  "Glasgow School of Art",
  "Heriot-Watt University",
  "University of the Highlands and Islands",
  "Queen Margaret University",
  "Robert Gordon University",
  "Royal Conservatoire of Scotland",
  "University of St Andrews",
  "University of Stirling",
  "University of Strathclyde",
  "University of the West of Scotland",

  // Wales
  "Aberystwyth University",
  "Bangor University",
  "Cardiff Metropolitan University",
  "Royal Welsh College of Music and Drama",
  "Swansea University",
  "University of Wales Trinity Saint David",
  "UWTSD Lampeter",

  // Northern Ireland
  "Ulster University",
  "Stranmillis University College",
  "St Mary's University College Belfast",

  // Further Education / Specialist
  "Arts University Bournemouth",
  "Arts University Plymouth",
  "Bishop Grosseteste University",
  "University of Chichester",
  "University of Chester",
  "Conservatoire for Dance and Drama",
  "Courtauld Institute of Art",
  "University for the Creative Arts",
  "Cranfield University",
  "University of Gloucestershire",
  "Leeds Arts University",
  "Leeds Beckett University",
  "Leeds Trinity University",
  "Liverpool Institute for Performing Arts",
  "Newman University",
  "University of Northumbria at Newcastle",
  "Plymouth Marjon University",
  "Ravensbourne University London",
  "Rose Bruford College",
  "Solent University",
  "University of St Mark and St John",
  "Writtle University College",
].sort();
